# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shoots Official
email: hello@shootsofficial.com
description: > # this means to ignore newlines until "baseurl:"
  A fashionable collaboration. Sharing our photo shoots and favourite things ☝️ Posts by Alanna Joanne, Maria Rubio and Jason Hargrove
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shootsofficial.com" # the base hostname & protocol for your site
twitter_username: shootsofficial
github_username:  shootsofficial
shareImage: "http://shootsofficial.com/assets/images/fashion-photo-maria-shoots-jasonhargrove-produced-alannajoanne.jpg"
contactEmail: hello@shootsofficial.com

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->

exclude: ['node_modules']
